# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\melanie jutras\workspace\DBApp\src\dbAppMainGui.ui'
#
# Created: Tue May 15 08:49:10 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Kozuka Mincho Pro M")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 50, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Minion Pro")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 100, 641, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ViewDatabase = QtGui.QWidget()
        self.tab_ViewDatabase.setObjectName("tab_ViewDatabase")
        self.pushButton_ViewTestResults = QtGui.QPushButton(self.tab_ViewDatabase)
        self.pushButton_ViewTestResults.setGeometry(QtCore.QRect(450, 350, 151, 51))
        self.pushButton_ViewTestResults.setObjectName("pushButton_ViewTestResults")
        self.groupBox = QtGui.QGroupBox(self.tab_ViewDatabase)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 611, 311))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget_testResults = QtGui.QTableWidget(self.groupBox)
        self.tableWidget_testResults.setGeometry(QtCore.QRect(10, 20, 591, 281))
        self.tableWidget_testResults.setObjectName("tableWidget_testResults")
        self.tableWidget_testResults.setColumnCount(0)
        self.tableWidget_testResults.setRowCount(0)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_ViewDatabase)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 340, 401, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser_dbLocation = QtGui.QTextBrowser(self.groupBox_2)
        self.textBrowser_dbLocation.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_dbLocation.setObjectName("textBrowser_dbLocation")
        self.pushButton_dbFileBrowse = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_dbFileBrowse.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_dbFileBrowse.setObjectName("pushButton_dbFileBrowse")
        self.tabWidget.addTab(self.tab_ViewDatabase, "")
        self.tab_MergeData = QtGui.QWidget()
        self.tab_MergeData.setObjectName("tab_MergeData")
        self.pushButton_MergeData = QtGui.QPushButton(self.tab_MergeData)
        self.pushButton_MergeData.setGeometry(QtCore.QRect(480, 350, 141, 51))
        self.pushButton_MergeData.setObjectName("pushButton_MergeData")
        self.groupBox_srcDB1 = QtGui.QGroupBox(self.tab_MergeData)
        self.groupBox_srcDB1.setGeometry(QtCore.QRect(100, 40, 401, 61))
        self.groupBox_srcDB1.setObjectName("groupBox_srcDB1")
        self.textBrowser_srcDB1 = QtGui.QTextBrowser(self.groupBox_srcDB1)
        self.textBrowser_srcDB1.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_srcDB1.setObjectName("textBrowser_srcDB1")
        self.pushButton_srcDB1 = QtGui.QPushButton(self.groupBox_srcDB1)
        self.pushButton_srcDB1.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_srcDB1.setObjectName("pushButton_srcDB1")
        self.groupBox_srcDB2 = QtGui.QGroupBox(self.tab_MergeData)
        self.groupBox_srcDB2.setGeometry(QtCore.QRect(100, 120, 401, 61))
        self.groupBox_srcDB2.setObjectName("groupBox_srcDB2")
        self.textBrowser_srcDB2 = QtGui.QTextBrowser(self.groupBox_srcDB2)
        self.textBrowser_srcDB2.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_srcDB2.setObjectName("textBrowser_srcDB2")
        self.pushButton_srcDB2 = QtGui.QPushButton(self.groupBox_srcDB2)
        self.pushButton_srcDB2.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_srcDB2.setObjectName("pushButton_srcDB2")
        self.groupBox_targetDB = QtGui.QGroupBox(self.tab_MergeData)
        self.groupBox_targetDB.setGeometry(QtCore.QRect(100, 240, 401, 61))
        self.groupBox_targetDB.setObjectName("groupBox_targetDB")
        self.textBrowser_targetDB = QtGui.QTextBrowser(self.groupBox_targetDB)
        self.textBrowser_targetDB.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_targetDB.setObjectName("textBrowser_targetDB")
        self.pushButton_targetDB = QtGui.QPushButton(self.groupBox_targetDB)
        self.pushButton_targetDB.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_targetDB.setObjectName("pushButton_targetDB")
        self.progressBar_merge = QtGui.QProgressBar(self.tab_MergeData)
        self.progressBar_merge.setGeometry(QtCore.QRect(230, 360, 118, 23))
        self.progressBar_merge.setProperty("value", 24)
        self.progressBar_merge.setObjectName("progressBar_merge")
        self.tabWidget.addTab(self.tab_MergeData, "")
        self.tab_DataAnalysis = QtGui.QWidget()
        self.tab_DataAnalysis.setObjectName("tab_DataAnalysis")
        self.label_3 = QtGui.QLabel(self.tab_DataAnalysis)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 171, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.tab_DataAnalysis)
        self.label_4.setGeometry(QtCore.QRect(370, 180, 181, 51))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_DataAnalysis, "")
        self.tab_CodeCoverage = QtGui.QWidget()
        self.tab_CodeCoverage.setObjectName("tab_CodeCoverage")
        self.pushButton_UpdateCodeCoverage = QtGui.QPushButton(self.tab_CodeCoverage)
        self.pushButton_UpdateCodeCoverage.setGeometry(QtCore.QRect(440, 280, 141, 51))
        self.pushButton_UpdateCodeCoverage.setObjectName("pushButton_UpdateCodeCoverage")
        self.progressBar_codeCoverage = QtGui.QProgressBar(self.tab_CodeCoverage)
        self.progressBar_codeCoverage.setGeometry(QtCore.QRect(150, 150, 331, 23))
        self.progressBar_codeCoverage.setProperty("value", 24)
        self.progressBar_codeCoverage.setObjectName("progressBar_codeCoverage")
        self.label_5 = QtGui.QLabel(self.tab_CodeCoverage)
        self.label_5.setGeometry(QtCore.QRect(210, 80, 201, 20))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_CodeCoverage, "")
        self.tab_DBAdmin = QtGui.QWidget()
        self.tab_DBAdmin.setObjectName("tab_DBAdmin")
        self.groupBox_DBAFileLoc = QtGui.QGroupBox(self.tab_DBAdmin)
        self.groupBox_DBAFileLoc.setGeometry(QtCore.QRect(20, 10, 431, 161))
        self.groupBox_DBAFileLoc.setObjectName("groupBox_DBAFileLoc")
        self.groupBox_defaultDBDir = QtGui.QGroupBox(self.groupBox_DBAFileLoc)
        self.groupBox_defaultDBDir.setGeometry(QtCore.QRect(10, 20, 401, 61))
        self.groupBox_defaultDBDir.setObjectName("groupBox_defaultDBDir")
        self.textBrowser_defaultDBLocation = QtGui.QTextBrowser(self.groupBox_defaultDBDir)
        self.textBrowser_defaultDBLocation.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_defaultDBLocation.setObjectName("textBrowser_defaultDBLocation")
        self.pushButton_defaultDBBrowse = QtGui.QPushButton(self.groupBox_defaultDBDir)
        self.pushButton_defaultDBBrowse.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_defaultDBBrowse.setObjectName("pushButton_defaultDBBrowse")
        self.groupBox_defaultTraceCRV = QtGui.QGroupBox(self.groupBox_DBAFileLoc)
        self.groupBox_defaultTraceCRV.setGeometry(QtCore.QRect(10, 90, 401, 61))
        self.groupBox_defaultTraceCRV.setObjectName("groupBox_defaultTraceCRV")
        self.textBrowser_defaultTraceLocation = QtGui.QTextBrowser(self.groupBox_defaultTraceCRV)
        self.textBrowser_defaultTraceLocation.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_defaultTraceLocation.setObjectName("textBrowser_defaultTraceLocation")
        self.pushButton_defaultTraceBrowse = QtGui.QPushButton(self.groupBox_defaultTraceCRV)
        self.pushButton_defaultTraceBrowse.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_defaultTraceBrowse.setObjectName("pushButton_defaultTraceBrowse")
        self.groupBox_DBAWorkstationInfo = QtGui.QGroupBox(self.tab_DBAdmin)
        self.groupBox_DBAWorkstationInfo.setGeometry(QtCore.QRect(20, 180, 431, 231))
        self.groupBox_DBAWorkstationInfo.setObjectName("groupBox_DBAWorkstationInfo")
        self.groupBox_defaultWorkstation1 = QtGui.QGroupBox(self.groupBox_DBAWorkstationInfo)
        self.groupBox_defaultWorkstation1.setGeometry(QtCore.QRect(10, 20, 401, 61))
        self.groupBox_defaultWorkstation1.setObjectName("groupBox_defaultWorkstation1")
        self.textBrowser_defaultWorkstation1 = QtGui.QTextBrowser(self.groupBox_defaultWorkstation1)
        self.textBrowser_defaultWorkstation1.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_defaultWorkstation1.setObjectName("textBrowser_defaultWorkstation1")
        self.pushButton_defaultWorkstation1 = QtGui.QPushButton(self.groupBox_defaultWorkstation1)
        self.pushButton_defaultWorkstation1.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_defaultWorkstation1.setObjectName("pushButton_defaultWorkstation1")
        self.groupBox_defaultWorkstation2 = QtGui.QGroupBox(self.groupBox_DBAWorkstationInfo)
        self.groupBox_defaultWorkstation2.setGeometry(QtCore.QRect(10, 90, 401, 61))
        self.groupBox_defaultWorkstation2.setObjectName("groupBox_defaultWorkstation2")
        self.textBrowser_defaultWorkstation2 = QtGui.QTextBrowser(self.groupBox_defaultWorkstation2)
        self.textBrowser_defaultWorkstation2.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_defaultWorkstation2.setObjectName("textBrowser_defaultWorkstation2")
        self.pushButton_defaultWorkstation2 = QtGui.QPushButton(self.groupBox_defaultWorkstation2)
        self.pushButton_defaultWorkstation2.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_defaultWorkstation2.setObjectName("pushButton_defaultWorkstation2")
        self.groupBox_defaultWorkstation3 = QtGui.QGroupBox(self.groupBox_DBAWorkstationInfo)
        self.groupBox_defaultWorkstation3.setGeometry(QtCore.QRect(10, 160, 401, 61))
        self.groupBox_defaultWorkstation3.setObjectName("groupBox_defaultWorkstation3")
        self.textBrowser_defaultWorkstation3 = QtGui.QTextBrowser(self.groupBox_defaultWorkstation3)
        self.textBrowser_defaultWorkstation3.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.textBrowser_defaultWorkstation3.setObjectName("textBrowser_defaultWorkstation3")
        self.pushButton_defaultWorkstation3 = QtGui.QPushButton(self.groupBox_defaultWorkstation3)
        self.pushButton_defaultWorkstation3.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButton_defaultWorkstation3.setObjectName("pushButton_defaultWorkstation3")
        self.tabWidget.addTab(self.tab_DBAdmin, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Knowlogic Software", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Test Results Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ViewTestResults.setText(QtGui.QApplication.translate("MainWindow", "View Test Results Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Test Results Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Database Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dbFileBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ViewDatabase), QtGui.QApplication.translate("MainWindow", "View Database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MergeData.setText(QtGui.QApplication.translate("MainWindow", "Merge Database Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_srcDB1.setTitle(QtGui.QApplication.translate("MainWindow", "Database 1 Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_srcDB1.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_srcDB2.setTitle(QtGui.QApplication.translate("MainWindow", "Database 2 Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_srcDB2.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_targetDB.setTitle(QtGui.QApplication.translate("MainWindow", "Merged Database Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_targetDB.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MergeData), QtGui.QApplication.translate("MainWindow", "Merge Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Module Defect Pie Chart Here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Revision Comparison Barchart Here", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DataAnalysis), QtGui.QApplication.translate("MainWindow", "Data Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_UpdateCodeCoverage.setText(QtGui.QApplication.translate("MainWindow", "Update With Latest Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Percentage of Statements Covered", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_CodeCoverage), QtGui.QApplication.translate("MainWindow", "Code Coverage", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_DBAFileLoc.setTitle(QtGui.QApplication.translate("MainWindow", "Default File Location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_defaultDBDir.setTitle(QtGui.QApplication.translate("MainWindow", "Default Database Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_defaultDBBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_defaultTraceCRV.setTitle(QtGui.QApplication.translate("MainWindow", "Default Trace File Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_defaultTraceBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_DBAWorkstationInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Workstation Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_defaultWorkstation1.setTitle(QtGui.QApplication.translate("MainWindow", "Workstation 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_defaultWorkstation1.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_defaultWorkstation2.setTitle(QtGui.QApplication.translate("MainWindow", "Workstation 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_defaultWorkstation2.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_defaultWorkstation3.setTitle(QtGui.QApplication.translate("MainWindow", "Workstation 3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_defaultWorkstation3.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DBAdmin), QtGui.QApplication.translate("MainWindow", "Database Administration", None, QtGui.QApplication.UnicodeUTF8))

