# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrtGui.ui'
#
# Created: Thu Nov 29 16:01:38 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 706)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setMargin(2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_18.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Config = QtGui.QWidget()
        self.tab_Config.setMinimumSize(QtCore.QSize(829, 440))
        self.tab_Config.setObjectName("tab_Config")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_Config)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_Config)
        self.groupBox_2.setMinimumSize(QtCore.QSize(621, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.projectFileSelector = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectFileSelector.sizePolicy().hasHeightForWidth())
        self.projectFileSelector.setSizePolicy(sizePolicy)
        self.projectFileSelector.setMinimumSize(QtCore.QSize(0, 0))
        self.projectFileSelector.setObjectName("projectFileSelector")
        self.horizontalLayout_5.addWidget(self.projectFileSelector)
        self.browseProjectFile = QtGui.QPushButton(self.groupBox_2)
        self.browseProjectFile.setMaximumSize(QtCore.QSize(16777152, 16777215))
        self.browseProjectFile.setObjectName("browseProjectFile")
        self.horizontalLayout_5.addWidget(self.browseProjectFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_userName = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_userName.sizePolicy().hasHeightForWidth())
        self.lineEdit_userName.setSizePolicy(sizePolicy)
        self.lineEdit_userName.setMaximumSize(QtCore.QSize(133, 20))
        self.lineEdit_userName.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_userName.setObjectName("lineEdit_userName")
        self.horizontalLayout_4.addWidget(self.lineEdit_userName)
        spacerItem = QtGui.QSpacerItem(388, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolOutput = QtGui.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.toolOutput.setFont(font)
        self.toolOutput.setReadOnly(True)
        self.toolOutput.setObjectName("toolOutput")
        self.horizontalLayout_6.addWidget(self.toolOutput)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.runAnalysis = QtGui.QPushButton(self.groupBox_2)
        self.runAnalysis.setObjectName("runAnalysis")
        self.verticalLayout_5.addWidget(self.runAnalysis)
        self.abortAnalysis = QtGui.QPushButton(self.groupBox_2)
        self.abortAnalysis.setObjectName("abortAnalysis")
        self.verticalLayout_5.addWidget(self.abortAnalysis)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.showPcLintLog = QtGui.QPushButton(self.groupBox_2)
        self.showPcLintLog.setObjectName("showPcLintLog")
        self.verticalLayout_5.addWidget(self.showPcLintLog)
        self.showKsLog = QtGui.QPushButton(self.groupBox_2)
        self.showKsLog.setObjectName("showKsLog")
        self.verticalLayout_5.addWidget(self.showKsLog)
        self.showToolOutput = QtGui.QPushButton(self.groupBox_2)
        self.showToolOutput.setObjectName("showToolOutput")
        self.verticalLayout_5.addWidget(self.showToolOutput)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab_Config)
        self.groupBox.setMinimumSize(QtCore.QSize(621, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.reviewedViolations = QtGui.QLineEdit(self.groupBox)
        self.reviewedViolations.setReadOnly(True)
        self.reviewedViolations.setObjectName("reviewedViolations")
        self.gridLayout.addWidget(self.reviewedViolations, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.acceptedViolations = QtGui.QLineEdit(self.groupBox)
        self.acceptedViolations.setReadOnly(True)
        self.acceptedViolations.setObjectName("acceptedViolations")
        self.gridLayout.addWidget(self.acceptedViolations, 6, 1, 1, 1)
        self.removedViolations = QtGui.QLineEdit(self.groupBox)
        self.removedViolations.setReadOnly(True)
        self.removedViolations.setObjectName("removedViolations")
        self.gridLayout.addWidget(self.removedViolations, 7, 1, 1, 1)
        self.ksTotal = QtGui.QLineEdit(self.groupBox)
        self.ksTotal.setReadOnly(True)
        self.ksTotal.setObjectName("ksTotal")
        self.gridLayout.addWidget(self.ksTotal, 0, 3, 1, 1)
        self.Reviewed = QtGui.QLabel(self.groupBox)
        self.Reviewed.setObjectName("Reviewed")
        self.gridLayout.addWidget(self.Reviewed, 5, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.ksReviewed = QtGui.QLineEdit(self.groupBox)
        self.ksReviewed.setReadOnly(True)
        self.ksReviewed.setObjectName("ksReviewed")
        self.gridLayout.addWidget(self.ksReviewed, 5, 3, 1, 1)
        self.ksAccepted = QtGui.QLineEdit(self.groupBox)
        self.ksAccepted.setReadOnly(True)
        self.ksAccepted.setObjectName("ksAccepted")
        self.gridLayout.addWidget(self.ksAccepted, 6, 3, 1, 1)
        self.ksRemoved = QtGui.QLineEdit(self.groupBox)
        self.ksRemoved.setReadOnly(True)
        self.ksRemoved.setObjectName("ksRemoved")
        self.gridLayout.addWidget(self.ksRemoved, 7, 3, 1, 1)
        self.pcReviewed = QtGui.QLineEdit(self.groupBox)
        self.pcReviewed.setReadOnly(True)
        self.pcReviewed.setObjectName("pcReviewed")
        self.gridLayout.addWidget(self.pcReviewed, 5, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 4, 1, 1)
        self.pcTotal = QtGui.QLineEdit(self.groupBox)
        self.pcTotal.setReadOnly(True)
        self.pcTotal.setObjectName("pcTotal")
        self.gridLayout.addWidget(self.pcTotal, 0, 5, 1, 1)
        self.pcAccepted = QtGui.QLineEdit(self.groupBox)
        self.pcAccepted.setReadOnly(True)
        self.pcAccepted.setObjectName("pcAccepted")
        self.gridLayout.addWidget(self.pcAccepted, 6, 5, 1, 1)
        self.pcRemoved = QtGui.QLineEdit(self.groupBox)
        self.pcRemoved.setReadOnly(True)
        self.pcRemoved.setObjectName("pcRemoved")
        self.gridLayout.addWidget(self.pcRemoved, 7, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.activeViolations = QtGui.QLineEdit(self.groupBox)
        self.activeViolations.setObjectName("activeViolations")
        self.gridLayout.addWidget(self.activeViolations, 3, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 2, 1, 1)
        self.ksActive = QtGui.QLineEdit(self.groupBox)
        self.ksActive.setObjectName("ksActive")
        self.gridLayout.addWidget(self.ksActive, 3, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 4, 1, 1)
        self.pcActive = QtGui.QLineEdit(self.groupBox)
        self.pcActive.setObjectName("pcActive")
        self.gridLayout.addWidget(self.pcActive, 3, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.totalViolations = QtGui.QLineEdit(self.groupBox)
        self.totalViolations.setReadOnly(True)
        self.totalViolations.setObjectName("totalViolations")
        self.gridLayout.addWidget(self.totalViolations, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.exportDb = QtGui.QPushButton(self.groupBox)
        self.exportDb.setObjectName("exportDb")
        self.gridLayout.addWidget(self.exportDb, 8, 5, 1, 1)
        self.openViolations = QtGui.QLineEdit(self.groupBox)
        self.openViolations.setObjectName("openViolations")
        self.gridLayout.addWidget(self.openViolations, 4, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 4, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 4, 2, 1, 1)
        self.ksOpen = QtGui.QLineEdit(self.groupBox)
        self.ksOpen.setObjectName("ksOpen")
        self.gridLayout.addWidget(self.ksOpen, 4, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 4, 4, 1, 1)
        self.pcOpen = QtGui.QLineEdit(self.groupBox)
        self.pcOpen.setObjectName("pcOpen")
        self.gridLayout.addWidget(self.pcOpen, 4, 5, 1, 1)
        self.clearedDbOfRemoved = QtGui.QPushButton(self.groupBox)
        self.clearedDbOfRemoved.setObjectName("clearedDbOfRemoved")
        self.gridLayout.addWidget(self.clearedDbOfRemoved, 8, 0, 1, 2)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_Config, "")
        self.tab_Analysis = QtGui.QWidget()
        self.tab_Analysis.setObjectName("tab_Analysis")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_Analysis)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_Filters = QtGui.QGroupBox(self.tab_Analysis)
        self.groupBox_Filters.setMinimumSize(QtCore.QSize(811, 141))
        self.groupBox_Filters.setObjectName("groupBox_Filters")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_Filters)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_Filename = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_Filename.setObjectName("comboBox_Filename")
        self.horizontalLayout.addWidget(self.comboBox_Filename)
        self.comboBox_Function = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_Function.setObjectName("comboBox_Function")
        self.horizontalLayout.addWidget(self.comboBox_Function)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtGui.QLabel(self.groupBox_Filters)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.lineEditDescFilter = QtGui.QLineEdit(self.groupBox_Filters)
        self.lineEditDescFilter.setObjectName("lineEditDescFilter")
        self.horizontalLayout_12.addWidget(self.lineEditDescFilter)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtGui.QLabel(self.groupBox_Filters)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.lineEditDetailsFilter = QtGui.QLineEdit(self.groupBox_Filters)
        self.lineEditDetailsFilter.setObjectName("lineEditDetailsFilter")
        self.horizontalLayout_3.addWidget(self.lineEditDetailsFilter)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_Severity = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_Severity.setObjectName("comboBox_Severity")
        self.horizontalLayout_2.addWidget(self.comboBox_Severity)
        self.comboBox_Id = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_Id.setObjectName("comboBox_Id")
        self.horizontalLayout_2.addWidget(self.comboBox_Id)
        self.comboBox_DetectedBy = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_DetectedBy.setObjectName("comboBox_DetectedBy")
        self.horizontalLayout_2.addWidget(self.comboBox_DetectedBy)
        self.comboBox_Status = QtGui.QComboBox(self.groupBox_Filters)
        self.comboBox_Status.setObjectName("comboBox_Status")
        self.horizontalLayout_2.addWidget(self.comboBox_Status)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.resetFilters = QtGui.QPushButton(self.groupBox_Filters)
        self.resetFilters.setObjectName("resetFilters")
        self.horizontalLayout_17.addWidget(self.resetFilters)
        spacerItem2 = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.dispositioned = QtGui.QCheckBox(self.groupBox_Filters)
        self.dispositioned.setObjectName("dispositioned")
        self.horizontalLayout_14.addWidget(self.dispositioned)
        self.pushButton_ApplyFilters = QtGui.QPushButton(self.groupBox_Filters)
        self.pushButton_ApplyFilters.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_ApplyFilters.setObjectName("pushButton_ApplyFilters")
        self.horizontalLayout_14.addWidget(self.pushButton_ApplyFilters)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.verticalLayout_14.addWidget(self.groupBox_Filters)
        self.groupBox_Violations = QtGui.QGroupBox(self.tab_Analysis)
        self.groupBox_Violations.setMinimumSize(QtCore.QSize(811, 200))
        self.groupBox_Violations.setObjectName("groupBox_Violations")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_Violations)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_Filename = QtGui.QLabel(self.groupBox_Violations)
        self.label_Filename.setObjectName("label_Filename")
        self.horizontalLayout_10.addWidget(self.label_Filename)
        self.textBrowser_Filename = QtGui.QLineEdit(self.groupBox_Violations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Filename.sizePolicy().hasHeightForWidth())
        self.textBrowser_Filename.setSizePolicy(sizePolicy)
        self.textBrowser_Filename.setReadOnly(True)
        self.textBrowser_Filename.setObjectName("textBrowser_Filename")
        self.horizontalLayout_10.addWidget(self.textBrowser_Filename)
        self.label_Function = QtGui.QLabel(self.groupBox_Violations)
        self.label_Function.setObjectName("label_Function")
        self.horizontalLayout_10.addWidget(self.label_Function)
        self.textBrowser_Function = QtGui.QLineEdit(self.groupBox_Violations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Function.sizePolicy().hasHeightForWidth())
        self.textBrowser_Function.setSizePolicy(sizePolicy)
        self.textBrowser_Function.setReadOnly(True)
        self.textBrowser_Function.setObjectName("textBrowser_Function")
        self.horizontalLayout_10.addWidget(self.textBrowser_Function)
        self.label_24 = QtGui.QLabel(self.groupBox_Violations)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.lineNumber = QtGui.QLineEdit(self.groupBox_Violations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineNumber.sizePolicy().hasHeightForWidth())
        self.lineNumber.setSizePolicy(sizePolicy)
        self.lineNumber.setObjectName("lineNumber")
        self.horizontalLayout_10.addWidget(self.lineNumber)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtGui.QLabel(self.groupBox_Violations)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.textBrowser_Severity = QtGui.QLineEdit(self.groupBox_Violations)
        self.textBrowser_Severity.setReadOnly(True)
        self.textBrowser_Severity.setObjectName("textBrowser_Severity")
        self.horizontalLayout_11.addWidget(self.textBrowser_Severity)
        self.label_Id = QtGui.QLabel(self.groupBox_Violations)
        self.label_Id.setObjectName("label_Id")
        self.horizontalLayout_11.addWidget(self.label_Id)
        self.textBrowser_Id = QtGui.QLineEdit(self.groupBox_Violations)
        self.textBrowser_Id.setReadOnly(True)
        self.textBrowser_Id.setObjectName("textBrowser_Id")
        self.horizontalLayout_11.addWidget(self.textBrowser_Id)
        self.label_DetectedBy = QtGui.QLabel(self.groupBox_Violations)
        self.label_DetectedBy.setObjectName("label_DetectedBy")
        self.horizontalLayout_11.addWidget(self.label_DetectedBy)
        self.textBrowser_DetectedBy = QtGui.QLineEdit(self.groupBox_Violations)
        self.textBrowser_DetectedBy.setReadOnly(True)
        self.textBrowser_DetectedBy.setObjectName("textBrowser_DetectedBy")
        self.horizontalLayout_11.addWidget(self.textBrowser_DetectedBy)
        self.label_25 = QtGui.QLabel(self.groupBox_Violations)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.reportedOn = QtGui.QLineEdit(self.groupBox_Violations)
        self.reportedOn.setObjectName("reportedOn")
        self.horizontalLayout_11.addWidget(self.reportedOn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser_Description = QTextEditClick(self.groupBox_Violations)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.textBrowser_Description.setFont(font)
        self.textBrowser_Description.setReadOnly(True)
        self.textBrowser_Description.setObjectName("textBrowser_Description")
        self.verticalLayout_7.addWidget(self.textBrowser_Description)
        self.textBrowser_Details = QTextEditClick(self.groupBox_Violations)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.textBrowser_Details.setFont(font)
        self.textBrowser_Details.setReadOnly(True)
        self.textBrowser_Details.setObjectName("textBrowser_Details")
        self.verticalLayout_7.addWidget(self.textBrowser_Details)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pcLintPdf = QtGui.QPushButton(self.groupBox_Violations)
        self.pcLintPdf.setObjectName("pcLintPdf")
        self.horizontalLayout_13.addWidget(self.pcLintPdf)
        self.horizontalScrollBar = QtGui.QScrollBar(self.groupBox_Violations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout_13.addWidget(self.horizontalScrollBar)
        self.syncCode = QtGui.QCheckBox(self.groupBox_Violations)
        self.syncCode.setObjectName("syncCode")
        self.horizontalLayout_13.addWidget(self.syncCode)
        self.pushButton_GotoCode = QtGui.QPushButton(self.groupBox_Violations)
        self.pushButton_GotoCode.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_GotoCode.setObjectName("pushButton_GotoCode")
        self.horizontalLayout_13.addWidget(self.pushButton_GotoCode)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.verticalLayout_16.addLayout(self.verticalLayout_8)
        self.verticalLayout_14.addWidget(self.groupBox_Violations)
        self.groupBox_Analysis = QtGui.QGroupBox(self.tab_Analysis)
        self.groupBox_Analysis.setMinimumSize(QtCore.QSize(811, 171))
        self.groupBox_Analysis.setObjectName("groupBox_Analysis")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_Analysis)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.clearAnalysis = QtGui.QPushButton(self.groupBox_Analysis)
        self.clearAnalysis.setObjectName("clearAnalysis")
        self.horizontalLayout_9.addWidget(self.clearAnalysis)
        self.cannedAnalysisSelector = QtGui.QComboBox(self.groupBox_Analysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cannedAnalysisSelector.sizePolicy().hasHeightForWidth())
        self.cannedAnalysisSelector.setSizePolicy(sizePolicy)
        self.cannedAnalysisSelector.setObjectName("cannedAnalysisSelector")
        self.horizontalLayout_9.addWidget(self.cannedAnalysisSelector)
        self.pushButtonAddCanned = QtGui.QPushButton(self.groupBox_Analysis)
        self.pushButtonAddCanned.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButtonAddCanned.setObjectName("pushButtonAddCanned")
        self.horizontalLayout_9.addWidget(self.pushButtonAddCanned)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.plainTextEdit_Analysis = QtGui.QTextEdit(self.groupBox_Analysis)
        self.plainTextEdit_Analysis.setObjectName("plainTextEdit_Analysis")
        self.verticalLayout_3.addWidget(self.plainTextEdit_Analysis)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtGui.QLabel(self.groupBox_Analysis)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.textBrowser_PrevReviewer = QtGui.QLineEdit(self.groupBox_Analysis)
        self.textBrowser_PrevReviewer.setMinimumSize(QtCore.QSize(30, 0))
        self.textBrowser_PrevReviewer.setReadOnly(True)
        self.textBrowser_PrevReviewer.setObjectName("textBrowser_PrevReviewer")
        self.horizontalLayout_16.addWidget(self.textBrowser_PrevReviewer)
        self.label_PrevDate = QtGui.QLabel(self.groupBox_Analysis)
        self.label_PrevDate.setObjectName("label_PrevDate")
        self.horizontalLayout_16.addWidget(self.label_PrevDate)
        self.textBrowser_PrevDate = QtGui.QLineEdit(self.groupBox_Analysis)
        self.textBrowser_PrevDate.setMinimumSize(QtCore.QSize(20, 0))
        self.textBrowser_PrevDate.setReadOnly(True)
        self.textBrowser_PrevDate.setObjectName("textBrowser_PrevDate")
        self.horizontalLayout_16.addWidget(self.textBrowser_PrevDate)
        self.label_PrevStatus = QtGui.QLabel(self.groupBox_Analysis)
        self.label_PrevStatus.setObjectName("label_PrevStatus")
        self.horizontalLayout_16.addWidget(self.label_PrevStatus)
        self.textBrowser_PrevStatus = QtGui.QLineEdit(self.groupBox_Analysis)
        self.textBrowser_PrevStatus.setMinimumSize(QtCore.QSize(20, 0))
        self.textBrowser_PrevStatus.setReadOnly(True)
        self.textBrowser_PrevStatus.setObjectName("textBrowser_PrevStatus")
        self.horizontalLayout_16.addWidget(self.textBrowser_PrevStatus)
        self.pushButton_MarkReviewed = QtGui.QPushButton(self.groupBox_Analysis)
        self.pushButton_MarkReviewed.setObjectName("pushButton_MarkReviewed")
        self.horizontalLayout_16.addWidget(self.pushButton_MarkReviewed)
        self.pushButton_MarkAccepted = QtGui.QPushButton(self.groupBox_Analysis)
        self.pushButton_MarkAccepted.setObjectName("pushButton_MarkAccepted")
        self.horizontalLayout_16.addWidget(self.pushButton_MarkAccepted)
        self.applyToAll = QtGui.QCheckBox(self.groupBox_Analysis)
        self.applyToAll.setObjectName("applyToAll")
        self.horizontalLayout_16.addWidget(self.applyToAll)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.verticalLayout_14.addWidget(self.groupBox_Analysis)
        self.tabWidget.addTab(self.tab_Analysis, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser_Filename_2 = QtGui.QLineEdit(self.tab)
        self.textBrowser_Filename_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Filename_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_Filename_2.setSizePolicy(sizePolicy)
        self.textBrowser_Filename_2.setReadOnly(False)
        self.textBrowser_Filename_2.setObjectName("textBrowser_Filename_2")
        self.gridLayout_3.addWidget(self.textBrowser_Filename_2, 0, 2, 1, 1)
        self.label_Function_2 = QtGui.QLabel(self.tab)
        self.label_Function_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_Function_2.setObjectName("label_Function_2")
        self.gridLayout_3.addWidget(self.label_Function_2, 0, 3, 1, 1)
        self.textBrowser_Function_2 = QtGui.QLineEdit(self.tab)
        self.textBrowser_Function_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Function_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_Function_2.setSizePolicy(sizePolicy)
        self.textBrowser_Function_2.setReadOnly(False)
        self.textBrowser_Function_2.setObjectName("textBrowser_Function_2")
        self.gridLayout_3.addWidget(self.textBrowser_Function_2, 0, 4, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 5, 1, 1)
        self.lineNumber_2 = QtGui.QLineEdit(self.tab)
        self.lineNumber_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineNumber_2.sizePolicy().hasHeightForWidth())
        self.lineNumber_2.setSizePolicy(sizePolicy)
        self.lineNumber_2.setReadOnly(False)
        self.lineNumber_2.setObjectName("lineNumber_2")
        self.gridLayout_3.addWidget(self.lineNumber_2, 0, 6, 1, 1)
        self.textBrowser_Description_2 = QTextEditClick(self.tab)
        self.textBrowser_Description_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.textBrowser_Description_2.setFont(font)
        self.textBrowser_Description_2.setDocumentTitle("")
        self.textBrowser_Description_2.setReadOnly(False)
        self.textBrowser_Description_2.setObjectName("textBrowser_Description_2")
        self.gridLayout_3.addWidget(self.textBrowser_Description_2, 6, 1, 1, 6)
        self.label_Filename_2 = QtGui.QLabel(self.tab)
        self.label_Filename_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_Filename_2.setObjectName("label_Filename_2")
        self.gridLayout_3.addWidget(self.label_Filename_2, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 4, 1, 1, 6)
        self.pushButtonSubmitManual = QtGui.QPushButton(self.tab)
        self.pushButtonSubmitManual.setEnabled(False)
        self.pushButtonSubmitManual.setObjectName("pushButtonSubmitManual")
        self.gridLayout_3.addWidget(self.pushButtonSubmitManual, 7, 1, 1, 6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_ProjFile = QtGui.QWidget()
        self.tab_ProjFile.setObjectName("tab_ProjFile")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_ProjFile)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtGui.QLabel(self.tab_ProjFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setFrameShadow(QtGui.QFrame.Raised)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.projFileSections = QtGui.QComboBox(self.tab_ProjFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projFileSections.sizePolicy().hasHeightForWidth())
        self.projFileSections.setSizePolicy(sizePolicy)
        self.projFileSections.setObjectName("projFileSections")
        self.horizontalLayout_19.addWidget(self.projFileSections)
        self.enableProjEdit = QtGui.QCheckBox(self.tab_ProjFile)
        self.enableProjEdit.setObjectName("enableProjEdit")
        self.horizontalLayout_19.addWidget(self.enableProjEdit)
        self.saveConfig = QtGui.QPushButton(self.tab_ProjFile)
        self.saveConfig.setObjectName("saveConfig")
        self.horizontalLayout_19.addWidget(self.saveConfig)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pfSections = QtGui.QListWidget(self.tab_ProjFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pfSections.sizePolicy().hasHeightForWidth())
        self.pfSections.setSizePolicy(sizePolicy)
        self.pfSections.setObjectName("pfSections")
        self.horizontalLayout_20.addWidget(self.pfSections)
        self.pfText = QtGui.QTextEdit(self.tab_ProjFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pfText.sizePolicy().hasHeightForWidth())
        self.pfText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.pfText.setFont(font)
        self.pfText.setReadOnly(True)
        self.pfText.setObjectName("pfText")
        self.horizontalLayout_20.addWidget(self.pfText)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.sectionTip = QtGui.QTextEdit(self.tab_ProjFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionTip.sizePolicy().hasHeightForWidth())
        self.sectionTip.setSizePolicy(sizePolicy)
        self.sectionTip.setMaximumSize(QtCore.QSize(16777215, 75))
        self.sectionTip.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sectionTip.setObjectName("sectionTip")
        self.verticalLayout_17.addWidget(self.sectionTip)
        self.tabWidget.addTab(self.tab_ProjFile, "")
        self.tab_MergeDb = QtGui.QWidget()
        self.tab_MergeDb.setObjectName("tab_MergeDb")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_MergeDb)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_26 = QtGui.QLabel(self.tab_MergeDb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 0, 1, 1)
        self.mergeProjectFileSelector = QtGui.QComboBox(self.tab_MergeDb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeProjectFileSelector.sizePolicy().hasHeightForWidth())
        self.mergeProjectFileSelector.setSizePolicy(sizePolicy)
        self.mergeProjectFileSelector.setMinimumSize(QtCore.QSize(0, 0))
        self.mergeProjectFileSelector.setObjectName("mergeProjectFileSelector")
        self.gridLayout_2.addWidget(self.mergeProjectFileSelector, 3, 2, 1, 1)
        self.browseMergeProjectFile = QtGui.QPushButton(self.tab_MergeDb)
        self.browseMergeProjectFile.setMaximumSize(QtCore.QSize(16777152, 16777215))
        self.browseMergeProjectFile.setObjectName("browseMergeProjectFile")
        self.gridLayout_2.addWidget(self.browseMergeProjectFile, 3, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 8, 2, 1, 1)
        self.mergeResults = QtGui.QTextEdit(self.tab_MergeDb)
        self.mergeResults.setObjectName("mergeResults")
        self.gridLayout_2.addWidget(self.mergeResults, 6, 2, 1, 1)
        self.mergeProgress = QtGui.QProgressBar(self.tab_MergeDb)
        self.mergeProgress.setProperty("value", 24)
        self.mergeProgress.setObjectName("mergeProgress")
        self.gridLayout_2.addWidget(self.mergeProgress, 5, 2, 1, 1)
        self.performMerge = QtGui.QPushButton(self.tab_MergeDb)
        self.performMerge.setObjectName("performMerge")
        self.gridLayout_2.addWidget(self.performMerge, 5, 3, 1, 1)
        self.mergeLabel = QtGui.QLabel(self.tab_MergeDb)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.mergeLabel.setFont(font)
        self.mergeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mergeLabel.setObjectName("mergeLabel")
        self.gridLayout_2.addWidget(self.mergeLabel, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_MergeDb)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_MergeDb, "")
        self.tab_Reports = QtGui.QWidget()
        self.tab_Reports.setObjectName("tab_Reports")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_Reports)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_srcCode = QtGui.QLabel(self.tab_Reports)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_srcCode.sizePolicy().hasHeightForWidth())
        self.label_srcCode.setSizePolicy(sizePolicy)
        self.label_srcCode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_srcCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_srcCode.setObjectName("label_srcCode")
        self.horizontalLayout_7.addWidget(self.label_srcCode)
        self.reportFileName = QtGui.QLineEdit(self.tab_Reports)
        self.reportFileName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportFileName.sizePolicy().hasHeightForWidth())
        self.reportFileName.setSizePolicy(sizePolicy)
        self.reportFileName.setObjectName("reportFileName")
        self.horizontalLayout_7.addWidget(self.reportFileName)
        self.pushButton_BrowseSrcCode = QtGui.QPushButton(self.tab_Reports)
        self.pushButton_BrowseSrcCode.setEnabled(False)
        self.pushButton_BrowseSrcCode.setObjectName("pushButton_BrowseSrcCode")
        self.horizontalLayout_7.addWidget(self.pushButton_BrowseSrcCode)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_reportDir = QtGui.QLabel(self.tab_Reports)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_reportDir.sizePolicy().hasHeightForWidth())
        self.label_reportDir.setSizePolicy(sizePolicy)
        self.label_reportDir.setObjectName("label_reportDir")
        self.horizontalLayout_8.addWidget(self.label_reportDir)
        self.reportDirectory = QtGui.QLineEdit(self.tab_Reports)
        self.reportDirectory.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportDirectory.sizePolicy().hasHeightForWidth())
        self.reportDirectory.setSizePolicy(sizePolicy)
        self.reportDirectory.setObjectName("reportDirectory")
        self.horizontalLayout_8.addWidget(self.reportDirectory)
        self.pushButton_BrowseReport = QtGui.QPushButton(self.tab_Reports)
        self.pushButton_BrowseReport.setEnabled(False)
        self.pushButton_BrowseReport.setObjectName("pushButton_BrowseReport")
        self.horizontalLayout_8.addWidget(self.pushButton_BrowseReport)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtGui.QSpacerItem(728, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem5 = QtGui.QSpacerItem(638, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.pushButton_GenerateReport = QtGui.QPushButton(self.tab_Reports)
        self.pushButton_GenerateReport.setEnabled(False)
        self.pushButton_GenerateReport.setObjectName("pushButton_GenerateReport")
        self.horizontalLayout_21.addWidget(self.pushButton_GenerateReport)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_Reports, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_13.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_userName, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.projectFileSelector)
        MainWindow.setTabOrder(self.projectFileSelector, self.browseProjectFile)
        MainWindow.setTabOrder(self.browseProjectFile, self.toolOutput)
        MainWindow.setTabOrder(self.toolOutput, self.runAnalysis)
        MainWindow.setTabOrder(self.runAnalysis, self.abortAnalysis)
        MainWindow.setTabOrder(self.abortAnalysis, self.reviewedViolations)
        MainWindow.setTabOrder(self.reviewedViolations, self.totalViolations)
        MainWindow.setTabOrder(self.totalViolations, self.acceptedViolations)
        MainWindow.setTabOrder(self.acceptedViolations, self.removedViolations)
        MainWindow.setTabOrder(self.removedViolations, self.ksTotal)
        MainWindow.setTabOrder(self.ksTotal, self.ksReviewed)
        MainWindow.setTabOrder(self.ksReviewed, self.ksAccepted)
        MainWindow.setTabOrder(self.ksAccepted, self.ksRemoved)
        MainWindow.setTabOrder(self.ksRemoved, self.pcReviewed)
        MainWindow.setTabOrder(self.pcReviewed, self.pcTotal)
        MainWindow.setTabOrder(self.pcTotal, self.pcAccepted)
        MainWindow.setTabOrder(self.pcAccepted, self.pcRemoved)
        MainWindow.setTabOrder(self.pcRemoved, self.activeViolations)
        MainWindow.setTabOrder(self.activeViolations, self.ksActive)
        MainWindow.setTabOrder(self.ksActive, self.pcActive)
        MainWindow.setTabOrder(self.pcActive, self.comboBox_Filename)
        MainWindow.setTabOrder(self.comboBox_Filename, self.comboBox_Function)
        MainWindow.setTabOrder(self.comboBox_Function, self.lineEditDescFilter)
        MainWindow.setTabOrder(self.lineEditDescFilter, self.lineEditDetailsFilter)
        MainWindow.setTabOrder(self.lineEditDetailsFilter, self.comboBox_Severity)
        MainWindow.setTabOrder(self.comboBox_Severity, self.comboBox_Id)
        MainWindow.setTabOrder(self.comboBox_Id, self.comboBox_DetectedBy)
        MainWindow.setTabOrder(self.comboBox_DetectedBy, self.comboBox_Status)
        MainWindow.setTabOrder(self.comboBox_Status, self.dispositioned)
        MainWindow.setTabOrder(self.dispositioned, self.pushButton_ApplyFilters)
        MainWindow.setTabOrder(self.pushButton_ApplyFilters, self.textBrowser_Filename)
        MainWindow.setTabOrder(self.textBrowser_Filename, self.textBrowser_Function)
        MainWindow.setTabOrder(self.textBrowser_Function, self.textBrowser_Severity)
        MainWindow.setTabOrder(self.textBrowser_Severity, self.textBrowser_Id)
        MainWindow.setTabOrder(self.textBrowser_Id, self.textBrowser_DetectedBy)
        MainWindow.setTabOrder(self.textBrowser_DetectedBy, self.textBrowser_Description)
        MainWindow.setTabOrder(self.textBrowser_Description, self.textBrowser_Details)
        MainWindow.setTabOrder(self.textBrowser_Details, self.syncCode)
        MainWindow.setTabOrder(self.syncCode, self.pushButton_GotoCode)
        MainWindow.setTabOrder(self.pushButton_GotoCode, self.cannedAnalysisSelector)
        MainWindow.setTabOrder(self.cannedAnalysisSelector, self.pushButtonAddCanned)
        MainWindow.setTabOrder(self.pushButtonAddCanned, self.plainTextEdit_Analysis)
        MainWindow.setTabOrder(self.plainTextEdit_Analysis, self.textBrowser_PrevReviewer)
        MainWindow.setTabOrder(self.textBrowser_PrevReviewer, self.textBrowser_PrevDate)
        MainWindow.setTabOrder(self.textBrowser_PrevDate, self.textBrowser_PrevStatus)
        MainWindow.setTabOrder(self.textBrowser_PrevStatus, self.pushButton_MarkReviewed)
        MainWindow.setTabOrder(self.pushButton_MarkReviewed, self.pushButton_MarkAccepted)
        MainWindow.setTabOrder(self.pushButton_MarkAccepted, self.projFileSections)
        MainWindow.setTabOrder(self.projFileSections, self.enableProjEdit)
        MainWindow.setTabOrder(self.enableProjEdit, self.saveConfig)
        MainWindow.setTabOrder(self.saveConfig, self.sectionTip)
        MainWindow.setTabOrder(self.sectionTip, self.reportFileName)
        MainWindow.setTabOrder(self.reportFileName, self.pushButton_BrowseSrcCode)
        MainWindow.setTabOrder(self.pushButton_BrowseSrcCode, self.reportDirectory)
        MainWindow.setTabOrder(self.reportDirectory, self.pushButton_BrowseReport)
        MainWindow.setTabOrder(self.pushButton_BrowseReport, self.pushButton_GenerateReport)
        MainWindow.setTabOrder(self.pushButton_GenerateReport, self.pcLintPdf)
        MainWindow.setTabOrder(self.pcLintPdf, self.reportedOn)
        MainWindow.setTabOrder(self.reportedOn, self.lineNumber)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CRMainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#55007f;\">Knowlogic Software</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#55007f;\">Code Review Tool</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Code Review Administration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Project File", None, QtGui.QApplication.UnicodeUTF8))
        self.browseProjectFile.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.runAnalysis.setText(QtGui.QApplication.translate("MainWindow", "Run Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.abortAnalysis.setText(QtGui.QApplication.translate("MainWindow", "Abort Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.showPcLintLog.setText(QtGui.QApplication.translate("MainWindow", "Show PC-Lint Log", None, QtGui.QApplication.UnicodeUTF8))
        self.showKsLog.setText(QtGui.QApplication.translate("MainWindow", "Show Knowlogic Log", None, QtGui.QApplication.UnicodeUTF8))
        self.showToolOutput.setText(QtGui.QApplication.translate("MainWindow", "Show Analysis Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Code Review Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Removed Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Reviewed Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Accepted Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.Reviewed.setText(QtGui.QApplication.translate("MainWindow", "Reviewed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Accepted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Removed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "PC-Lint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Reviewed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Accepted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Removed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Active Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Knowlogic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Total Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.exportDb.setText(QtGui.QApplication.translate("MainWindow", "Export Database to CSV File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Open Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.clearedDbOfRemoved.setText(QtGui.QApplication.translate("MainWindow", "Delete \'Removed Violations\' from DB", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Config), QtGui.QApplication.translate("MainWindow", "Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Filters.setTitle(QtGui.QApplication.translate("MainWindow", "Select Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Description Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Details Filter :", None, QtGui.QApplication.UnicodeUTF8))
        self.resetFilters.setText(QtGui.QApplication.translate("MainWindow", "Reset Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.dispositioned.setText(QtGui.QApplication.translate("MainWindow", "Include Dispositioned", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ApplyFilters.setText(QtGui.QApplication.translate("MainWindow", "Apply Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Violations.setTitle(QtGui.QApplication.translate("MainWindow", "View Violations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Filename.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Function.setText(QtGui.QApplication.translate("MainWindow", "Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Line:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Severity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Id.setText(QtGui.QApplication.translate("MainWindow", "Violation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DetectedBy.setText(QtGui.QApplication.translate("MainWindow", "Detected By:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Reported On:", None, QtGui.QApplication.UnicodeUTF8))
        self.pcLintPdf.setText(QtGui.QApplication.translate("MainWindow", "PC-Lint Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.syncCode.setText(QtGui.QApplication.translate("MainWindow", "Auto-GoTo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_GotoCode.setText(QtGui.QApplication.translate("MainWindow", "Go To Code", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Analysis.setTitle(QtGui.QApplication.translate("MainWindow", "Enter Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAnalysis.setText(QtGui.QApplication.translate("MainWindow", "Clear Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddCanned.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Reviewer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PrevDate.setText(QtGui.QApplication.translate("MainWindow", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PrevStatus.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MarkReviewed.setText(QtGui.QApplication.translate("MainWindow", "Mark Reviewed", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MarkAccepted.setText(QtGui.QApplication.translate("MainWindow", "Mark Accepted", None, QtGui.QApplication.UnicodeUTF8))
        self.applyToAll.setText(QtGui.QApplication.translate("MainWindow", "Apply to All", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Analysis), QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Function_2.setText(QtGui.QApplication.translate("MainWindow", "Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Line:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Filename_2.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSubmitManual.setText(QtGui.QApplication.translate("MainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Manual Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Project File Sections", None, QtGui.QApplication.UnicodeUTF8))
        self.enableProjEdit.setText(QtGui.QApplication.translate("MainWindow", "Enable Editing", None, QtGui.QApplication.UnicodeUTF8))
        self.saveConfig.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ProjFile), QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Merge Project", None, QtGui.QApplication.UnicodeUTF8))
        self.browseMergeProjectFile.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.performMerge.setText(QtGui.QApplication.translate("MainWindow", "Perform Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeLabel.setText(QtGui.QApplication.translate("MainWindow", "C:/Knowlogic/tools/CR-Projs/G4-B/G4B.crp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Select the project file you would like to merge with this project:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MergeDb), QtGui.QApplication.translate("MainWindow", "Merge Project", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Reports.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a File to get a report on.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_srcCode.setText(QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_BrowseSrcCode.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_reportDir.setText(QtGui.QApplication.translate("MainWindow", "Report Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_BrowseReport.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_GenerateReport.setText(QtGui.QApplication.translate("MainWindow", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Reports), QtGui.QApplication.translate("MainWindow", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))

from qtexteditclick import QTextEditClick
